#format specifier

price1 = 36765.1
price2 = -966.567
price3 = 12.34

#print(f"the price1 is ${price1: .2f}")
#print(f"the price2 is ${price2: .2f}")
#print(f"the price3 is ${price3: .2f}")           #f = format

#print(f"the price1 is {price1: 10}")              #10spaces
#print(f"the price2 is {price2: 10}")
#print(f"the price3 is {price3: 10}")

#print(f"the price1 is {price1:010}")
#print(f"the price1 is {price2:010}")

#print(f"the price1 is ${price1:<10}")             #  < = left side
                                                                                     
#print(f"the price1 is ${price1:>10}")             #  > = right side    

#print(f"the price1 is ${price1:^10}")             #   ^ =  in center

#print(f"the price1 is ${price1:+}")             
#print(f"the price2 is ${price2:+}")             

#print(f"the price1 is ${price1:,}")             

#print(f"the price1 is ${price1:+,.2f}")
#print(f"the price2 is ${price2:+,.2f}")             #   ^ =  in center
